baseURL = "https://geofila.github.io/"
googleAnalytics = "UA/G-W3R0C8HCBQ"

languageCode = "en-us"
theme = "avicenna"
title = "Giorgos Filandrianos"

[params]
# for the copy-right section of your page
name = "Giorgos Filandrianos"
